/**
 * Aigarth stake service — Phase 20.4.
 *
 * Thin service-layer wrapper around the AigarthPool client. The
 * HTTP layer talks to this; the AigarthPool client is the
 * canonical state machine (in simulator mode) or the Qubic RPC
 * backend (in qpi mode, hardware-gated).
 *
 * No off-chain mirror table in this push — the off-chain world
 * relies entirely on the AigarthPool client as the source of
 * truth. A future PR can add an `aigarth_stakes` mirror table
 * populated by the watcher in services/qubic.
 */

import { getAigarthPool } from "./aigarthpool.js";
import type { Position, YieldOwed } from "@aigarth/aigarthpool";

/**
 * Stake `amount` QUBIC for an ANN on behalf of `user`. The
 * `qearnLockId` is generated by the AigarthPool client; the
 * caller doesn't see it.
 */
export async function stakeForAnn(
  userWallet: string,
  annId: string,
  amount: bigint,
  weeks: number,
): Promise<Position> {
  const pool = getAigarthPool();
  return pool.stakeForAnn(userWallet, annId, amount, weeks);
}

/**
 * Extend an existing lock.
 */
export async function extendLock(
  userWallet: string,
  annId: string,
  additionalWeeks: number,
): Promise<Position> {
  const pool = getAigarthPool();
  return pool.extendLock(userWallet, annId, additionalWeeks);
}

/**
 * Start the unlock for a position. The yield is split; principal
 * + user share are owed.
 */
export async function unlock(userWallet: string, annId: string): Promise<void> {
  const pool = getAigarthPool();
  await pool.unlock(userWallet, annId);
}

/**
 * Claim principal + user share of yield for a previously unlocked
 * position. Idempotent.
 */
export async function claimRewards(
  userWallet: string,
  annId: string,
): Promise<{ principal: bigint; yield: bigint }> {
  const pool = getAigarthPool();
  return pool.claimRewards(userWallet, annId);
}

/**
 * Query a user's active position for an ANN.
 */
export async function getPosition(
  userWallet: string,
  annId: string,
): Promise<Position | null> {
  const pool = getAigarthPool();
  return pool.getPosition(userWallet, annId);
}

/**
 * Query a user's owed rewards for an ANN (post-unlock, pre-claim).
 */
export async function getYieldOwed(
  userWallet: string,
  annId: string,
): Promise<YieldOwed | null> {
  const pool = getAigarthPool();
  return pool.getYieldOwed(userWallet, annId);
}
