/**
 * Qearn watcher worker — Phase 23.3 (p3).
 *
 * Observes transactions addressed to the Qearn contract and
 * mirrors them into the `qubic_qearn_events` table. services/economy
 * subscribes to the same events (via NATS) to drive compute-grant
 * allocations.
 *
 * The watcher is hardware-gated for the real Qubic RPC client:
 *   - In stub mode (default for dev/test), it polls the
 *     StubQubicClient's broadcast log. Every broadcastStake to the
 *     Qearn contract shows up in the next poll. Useful for local
 *     smoke tests.
 *   - In http mode, it polls the Qubic gateway's
 *     /v1/addresses/{qearn}/transactions endpoint. Production.
 *   - Subscription mode (real-time) is a future improvement once
 *     the Qubic gateway exposes a websocket feed.
 *
 * Per-event classification:
 *   - amount > 0  → "lock"   (user locked QUBIC into Qearn)
 *   - amount == 0 → "unlock" (user requested unlock of a Qearn lock)
 *   - anything else addressed to Qearn → "other"
 *
 * Idempotency: events are unique on `tx_hash`. The watcher keeps
 * a "last seen tick" in memory; restartable from any tick via
 * the `fromTick` option to `getTransactionHistory`.
 *
 * Run: `pnpm --filter @aigarth/qubic worker:qearn-watcher`
 *
 * Disable: set `QEARN_WATCHER_ENABLED=false` in services/qubic/.env.
 */

import { eq, sql } from "drizzle-orm";
import { connect, type NatsConnection } from "nats";
import { loadConfig } from "../config/index.js";
import { getQubicClient, type QubicTransaction } from "../client/index.js";
import { closeDb, getDb } from "../db/index.js";
import { qubicQearnEvents } from "../db/schema.js";
import { logActivity } from "../lib/audit.js";

const log = (level: "info" | "warn" | "error", msg: string, extra?: Record<string, unknown>) => {
  // eslint-disable-next-line no-console
  console[level === "info" ? "log" : level](
    JSON.stringify({ ts: new Date().toISOString(), level, service: "qearn-watcher", msg, ...extra }),
  );
};

interface QearnClientLike {
  getTransactionHistory(
    address: string,
    options?: { limit?: number; fromTick?: number },
  ): Promise<QubicTransaction[]>;
  getCurrentTick(): Promise<{ tickNumber: number; epoch: number }>;
}

function getQearnContractAddress(cfg: ReturnType<typeof loadConfig>): string {
  // services/qubic's local concept; the real Qearn contract address
  // is read from the Qubic contract registry at deploy time. For
  // dev/test, the stub uses the constant "QEARN" + 55 A's.
  return cfg.QUBIC_QEARN_CONTRACT_ADDRESS || "QEARN" + "A".repeat(55);
}

/**
 * Classify a Qearn transaction into a high-level event kind.
 * Heuristic; the real Qubic gateway will return a structured
 * `procedure_index` field that makes this exact.
 */
function classifyQearnTx(tx: QubicTransaction, qearnAddress: string): {
  kind: "lock" | "unlock" | "other";
  lockId: string | null;
} {
  if (tx.toAddress !== qearnAddress) {
    return { kind: "other", lockId: null };
  }
  const amountQubic: bigint =
    typeof tx.amountQubic === "string" ? BigInt(tx.amountQubic) : tx.amountQubic;
  if (amountQubic > 0n) {
    // A lock; the resulting Qearn lock id is generated by Qearn and
    // returned via the broadcast result. The watcher doesn't have
    // access to that here — leave lockId null and let downstream
    // services resolve it via the tx hash.
    return { kind: "lock", lockId: null };
  }
  return { kind: "unlock", lockId: null };
}

async function alreadyPersisted(txHash: string): Promise<boolean> {
  const db = getDb();
  const row = await db
    .select({ id: qubicQearnEvents.id })
    .from(qubicQearnEvents)
    .where(eq(qubicQearnEvents.txHash, txHash))
    .limit(1);
  return row.length > 0;
}

async function persistEvent(
  tx: QubicTransaction,
  kind: "lock" | "unlock" | "other",
  lockId: string | null,
  observedAtTick: number,
): Promise<void> {
  const db = getDb();
  const amountQubic: bigint =
    typeof tx.amountQubic === "string" ? BigInt(tx.amountQubic) : tx.amountQubic;
  await db
    .insert(qubicQearnEvents)
    .values({
      txHash: tx.txHash,
      fromAddress: tx.fromAddress,
      toAddress: tx.toAddress,
      amountQubic,
      tickNumber: tx.tickNumber,
      kind,
      lockId,
      observedAtTick,
      metadata: {
        status: tx.status,
        sourceTimestamp: tx.timestamp,
      },
    })
    // On conflict (restart of the watcher, race), keep the existing row.
    .onConflictDoNothing({ target: qubicQearnEvents.txHash });
}

async function publishNats(
  nc: NatsConnection | null,
  subject: string,
  payload: Record<string, unknown>,
): Promise<void> {
  if (!nc) return;  // NATS unavailable — best-effort, log only.
  try {
    nc.publish(subject, JSON.stringify(payload));
  } catch (err) {
    log("warn", "nats publish failed", { subject, error: (err as Error).message });
  }
}

async function processTick(
  cfg: ReturnType<typeof loadConfig>,
  client: QearnClientLike,
  qearnAddress: string,
  nc: NatsConnection | null,
  lastSeenTick: { value: number },
): Promise<number> {
  const tick = await client.getCurrentTick();
  const history = await client.getTransactionHistory(qearnAddress, {
    limit: 100,
    fromTick: lastSeenTick.value + 1,  // skip already-seen
  });

  let processed = 0;
  for (const tx of history) {
    if (await alreadyPersisted(tx.txHash)) continue;
    const { kind, lockId } = classifyQearnTx(tx, qearnAddress);
    await persistEvent(tx, kind, lockId, tick.tickNumber);
    await logActivity(getDb(), {
      action: `qearn.${kind}`,
      actorUserId: null,
      orgId: null,
      targetType: "qearn",
      targetId: tx.txHash,
      metadata: {
        fromAddress: tx.fromAddress,
        amountQubic: tx.amountQubic.toString(),
        tickNumber: tx.tickNumber,
      },
    });
    await publishNats(nc, cfg.NATS_QEARN_SUBJECT, {
      kind,
      txHash: tx.txHash,
      fromAddress: tx.fromAddress,
      amountQubic: tx.amountQubic.toString(),
      tickNumber: tx.tickNumber,
      observedAtTick: tick.tickNumber,
      lockId,
    });
    processed += 1;
    if (tx.tickNumber > lastSeenTick.value) lastSeenTick.value = tx.tickNumber;
  }

  return processed;
}

async function main() {
  const cfg = loadConfig();
  if (!cfg.QEARN_WATCHER_ENABLED) {
    log("info", "qearn-watcher disabled (QEARN_WATCHER_ENABLED=false), exiting");
    return;
  }
  // Touch getDb to fail fast on misconfiguration
  getDb();
  const qearnAddress = getQearnContractAddress(cfg);

  // Connect to NATS (best-effort — the watcher works without it, just
  // no downstream fan-out). A connection failure is logged but does
  // not stop the loop.
  let nc: NatsConnection | null = null;
  try {
    nc = await connect({ servers: cfg.NATS_URL, timeout: 2_000 });
    log("info", "nats connected", { url: cfg.NATS_URL, subject: cfg.NATS_QEARN_SUBJECT });
  } catch (err) {
    log("warn", "nats unavailable — continuing without downstream publish", {
      url: cfg.NATS_URL,
      error: (err as Error).message,
    });
  }

  const client = getQubicClient() as QearnClientLike;
  const lastSeenTick = { value: 0 };

  log("info", "starting qearn-watcher", {
    qearnAddress,
    pollIntervalMs: cfg.QEARN_WATCHER_POLL_INTERVAL_MS,
    natsSubject: cfg.NATS_QEARN_SUBJECT,
    clientMode: cfg.QUBIC_CLIENT_MODE,
  });

  // Graceful shutdown
  let running = true;
  for (const sig of ["SIGINT", "SIGTERM"] as const) {
    process.once(sig, () => {
      running = false;
      log("info", `${sig} received, shutting down`);
    });
  }

  // Initial tick — log the watermark.
  try {
    const initial = await client.getCurrentTick();
    lastSeenTick.value = initial.tickNumber;
    log("info", "initial tick", { tick: initial.tickNumber, epoch: initial.epoch });
  } catch (err) {
    log("warn", "could not fetch initial tick; starting from 0", {
      error: (err as Error).message,
    });
  }

  while (running) {
    try {
      const processed = await processTick(cfg, client, qearnAddress, nc, lastSeenTick);
      if (processed > 0) {
        log("info", "tick processed", { processed, lastSeenTick: lastSeenTick.value });
      }
    } catch (err) {
      log("error", "tick processing failed", {
        error: err instanceof Error ? err.message : String(err),
      });
    }
    await sleep(cfg.QEARN_WATCHER_POLL_INTERVAL_MS);
  }

  if (nc) {
    try {
      await nc.drain();
    } catch {
      // best-effort
    }
  }
  await closeDb();
  // Touch sql import to keep it explicit (used for potential future
  // aggregation queries on this side of the watcher).
  void sql;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error("qearn-watcher crashed:", err);
  process.exit(1);
});
